### PR TITLE
feat: use https for backend and add test cert

### PR DESCRIPTION
**Pull request by ctrlc03**

### CODE REVIEW

**Review by JohnGuilding — COMMENTED** [review]
Thoughts on updating the frontend so that it works with these changes as part of this PR?

**Comment by ctrlc03** [comment]
> Thoughts on updating the frontend so that it works with these changes as part of this PR?

good point, will do that

**Comment by ctrlc03** [comment]
> > Thoughts on updating the frontend so that it works with these changes as part of this PR?
> 
> good point, will do that

@JohnGuilding updated frontend to accept url from .env - first time use you'll need to navigate to https://localhost:3001 and approve self signed cert before the frontend can use it (will need proper cert for backend to use https in prod)

**Review by JohnGuilding — APPROVED** [review]
lfg

**Pull request merged**
